export const GET_EQUIPMENTS_REQUEST = "GET_EQUIPMENTS_REQUEST";
export const GET_EQUIPMENTS_SUCCESS = "GET_EQUIPMENTS_SUCCESS";
export const GET_EQUIPMENTS_FAIL = "GET_EQUIPMENTS_FAIL";

export const GET_EQUIPMENT_DETAILS_REQUEST = "GET_EQUIPMENT_DETAILS_REQUEST";
export const GET_EQUIPMENT_DETAILS_SUCCESS = "GET_EQUIPMENT_DETAILS_SUCCESS";
export const GET_EQUIPMENT_DETAILS_FAIL = "GET_EQUIPMENT_DETAILS_FAIL";
